title: 'WMI'
subtitle: 'Website Management Indonesia'
description: Website Management Indonesia is a blog about scripts, tips and tricks, games, software. Covering php, javascript, jquery, mysql, seo, e-commerce and others.
author: "L3n4r0x"
keywords: the legend of neverland, genshin impact, games, how to, tips and tricks, php, javascript, jquery, mysql, seo, e-commerce
timezone: 'Asia/Jakarta'
language:
  - id # Bahasa Indonesia
  - en # Default language
  - zh-TW # Traditional Chinese
  - zh-CN # Simplified Chinese
  - zh-HK
  - th # Thailand
  - tl # Filipino

url: https://www.webmanajemen.com/
root: /
permalink: :title.html
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

post_dir: "src-posts"
public_dir: "dist"
source_dir: "source"

default_category: uncategorized
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true

# https://github.com/hexojs/hexo-util
# https://hexo.io/docs/syntax-highlight.html
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: '  ' # replace tabs with 2 spaces
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

generator:
  cache: false
  image:
    type: 'url'

hexo-shortcodes:
  raw: true # hexo-shortcodes return as markdown instead of html

exclude:
  - '**/.git*'
  - '**/.git'
  - '**/.vscode'
  - '**/.idea'
  - '**/.env'
  - '**/License.md'
  - '**/frontmatter.json'
  - '**/.frontmatter'
  - '**/git-hooks'
  - '**/License'
  - '**/bin/**'
  - '**/backend/**'
  - '**/MIDI.js/**'
  - '**/{readme,README,changelog,CHANGELOG,license,LICENSE,License}.md'
  - '**/Test/**'
  - '**/guzzle/**'
  - '**/exclude/**'
  - '**/hexo-post-parser/**'
  - '**/node_modules/**'
  - '**/vendor/**'
  - '**/ads/**'
  - '**/tmp/**'
  - '**/hexo-theme-unit-test/**'
  - '**/*-backup*'